Repository jigintern/real-2024-b, pull requests merged in 2024-08, with the labels that each got.

#17 👍 update wsclient.js, server.js, main.html
  public/main.html
  public/wsclient.js
  server.js
Labels: enhancement

#19 ✨ add：最近の出来事の写真をアップロードする機能を追加
  public/index.html
  public/main.html
  public/style.css
Labels: enhancement

#20 Add footer　HELP!!!
  public/img/footer_edit.png
  public/img/footer_home.png
  public/img/footer_search.png
  public/main.html
  public/style.css
Labels: enhancement, help wanted

#26 🎨 refactor：画像サイズを圧縮する処理を追加
  public/compressImg.js
  public/index.html
Labels: enhancement

#29 Feature/save activity image
  public/wsclient.js
  server.js
Labels: enhancement

#31 ✨ add：ファビコンの追加
  public/img/favicon/android-chrome-192x192.png
  public/img/favicon/apple-touch-icon.png
  public/img/favicon/favicon-16x16.png
  public/img/favicon/favicon-32x32.png
  public/img/favicon/favicon.ico
  public/img/favicon/mstile-150x150.png
  public/img/favicon/safari-pinned-tab.svg
  public/index.html
  public/main.html
  public/match.html
Labels: enhancement

#32 バグを直しました
  public/wsclient.js
Labels: help wanted

#36 マッチング成功したときにデータをdenokvに保存するやつ
  server.js
Labels: enhancement

#40 Update Branch
  public/img/favicon/android-chrome-192x192.png
  public/img/favicon/apple-touch-icon.png
  public/img/favicon/favicon-16x16.png
  public/img/favicon/favicon-32x32.png
  public/img/favicon/favicon.ico
  public/img/favicon/mstile-150x150.png
  public/img/favicon/safari-pinned-tab.svg
  public/index.html
  public/main.html
  public/match.html
  public/wsclient.js
  server.js
Labels: help wanted
